- project:
    templates:
      - openstack-lower-constraints-jobs-neutron
      - openstack-python3-yoga-jobs-neutron
      - publish-openstack-docs-pti
      - check-requirements
      - release-notes-jobs-python3
    check:
      jobs:
        - openstack-tox-docs:
            required-projects:
              - openstack/neutron
    gate:
      jobs:
        - openstack-tox-docs:
            required-projects:
              - openstack/neutron
