- project:
    templates:
      - openstack-python-jobs-neutron
      - publish-openstack-docs-pti
      - check-requirements
      - openstack-python3-train-jobs-neutron
      - release-notes-jobs-python3
